/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Forms.Menu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


public class prev extends javax.swing.JFrame {

    public prev(Object[][] data) {
        initComponents();
        populateTable(data);
        receipt();
    }
    private void populateTable(Object[][] data) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (Object[] row : data) {
            model.addRow(row);
        }
    }
        
    public void receipt() {
        // bill print
        
        try {
            StringBuilder receipt = new StringBuilder();

    // Order details
            String orderNumber = "12345"; // Example order number
            String orderDate = "2024-06-10"; // Example order date
            receipt.append("========================== ORDER PREVIEW ===================\n");
            receipt.append(String.format("%-20s: %s\n", "Order Number", orderNumber));
            receipt.append(String.format("%-20s: %s\n", "Order Date", orderDate));
            receipt.append("============================================================\n\n");

    // Header for product details
            receipt.append(String.format("%-30s %10s %40s\n", "Name", "Qty", "Price"));
            receipt.append("------------------------------------------------------------------------------------------------------------\n");

    DefaultTableModel df = (DefaultTableModel) jTable1.getModel();

    // Get table Product details and calculate total quantity
            int totalQty = 0;
            double totalPrice = 0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String Name = df.getValueAt(i, 1).toString();
                String Qty = df.getValueAt(i, 2).toString();
                String Price = df.getValueAt(i, 3).toString();
                totalQty += Integer.parseInt(Qty);
                totalPrice += Double.parseDouble(Price);
                receipt.append(String.format("%-30s %10s %40s\n", Name, Qty, Price));
                }

    // Footer for summary
            receipt.append("------------------------------------------------------------------------------------------------------------\n");
            receipt.append(String.format("%-30s %10d %40s\n", "Total Quantity", totalQty, totalPrice));
            receipt.append("\n============================================================\n");
            receipt.append("       MAKE SURE YOUR ORDERS ARE CORRECT BEFORE PROCEEDING!\n");
            receipt.append("==============================================================\n");

            prebyu.setText(receipt.toString());
    } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);   
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        prebyu = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        prebyu.setEditable(false);
        prebyu.setColumns(20);
        prebyu.setRows(5);
        jScrollPane1.setViewportView(prebyu);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //TentNumber tent = new TentNumber();
        //tent.setVisible(true);
        this.hide();
        TentNumber tent = new TentNumber();
        tent.setVisible(true);
        tent.setLocationRelativeTo(null);
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openRisebu();
            }
        });
        // Ensure the timer only runs once
        timer.setRepeats(false);
        // Start the timer
        timer.start();     
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private Object[][] getTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowCount = model.getRowCount();
        Object[][] data = new Object[rowCount][4]; // Four columns: item, name, qty, and price
        for (int i = 0; i < rowCount; i++) {
            data[i][0] = model.getValueAt(i, 0); // Item
            data[i][1] = model.getValueAt(i, 1); // Name
            data[i][2] = model.getValueAt(i, 2); // Qty
            data[i][3] = model.getValueAt(i, 3); // Price
        }
        return data;
    }
    
    private void openRisebu() {
        risebu rebisco = new risebu(getTableData());
        rebisco.setLocationRelativeTo(null);
        rebisco.setVisible(true);
        
    }
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea prebyu;
    // End of variables declaration//GEN-END:variables
}
